function identity = bistatic_artifact_content_identity( ...
        artifacts, configSha256)
%BISTATIC_ARTIFACT_CONTENT_IDENTITY Hash project artifact identity and arrays.
% The semantic-v1 digest is independent of MAT-file serialization. Source
% file bytes are bound separately by bistatic_make_cp_ofdm_descriptor.

if ~isstruct(artifacts) || ~isscalar(artifacts)
    error('bistatic:ArtifactContentIdentityType', ...
        'artifacts must be a scalar struct.');
end
required = {'artifact_class', 'production_allowed', 'resolved_by', ...
    'preamble_fd', 'pilot_mask_active_by_payload', ...
    'pilot_values_active_by_payload'};
for index = 1:numel(required)
    if ~isfield(artifacts, required{index})
        error('bistatic:ArtifactContentIdentityField', ...
            'artifacts is missing required field %s.', required{index});
    end
end
artifactClass = textScalar(artifacts.artifact_class, ...
    'artifacts.artifact_class');
resolvedBy = textScalar(artifacts.resolved_by, ...
    'artifacts.resolved_by');
configSha256 = sha256Text(configSha256, 'configSha256');
if ~islogical(artifacts.production_allowed) || ...
        ~isscalar(artifacts.production_allowed)
    error('bistatic:ArtifactContentIdentityProduction', ...
        'artifacts.production_allowed must be a logical scalar.');
end
if ~isa(artifacts.preamble_fd, 'double') || ...
        any(~isfinite(real(artifacts.preamble_fd)), 'all') || ...
        any(~isfinite(imag(artifacts.preamble_fd)), 'all') || ...
        ~islogical(artifacts.pilot_mask_active_by_payload) || ...
        ~isa(artifacts.pilot_values_active_by_payload, 'double') || ...
        any(~isfinite(real(artifacts.pilot_values_active_by_payload)), 'all') || ...
        any(~isfinite(imag(artifacts.pilot_values_active_by_payload)), 'all')
    error('bistatic:ArtifactContentIdentityNumeric', ...
        'Artifact component arrays have invalid types or nonfinite values.');
end

component.preamble_fd = complexDoubleSha256(artifacts.preamble_fd);
component.pilot_mask = logicalArraySha256( ...
    artifacts.pilot_mask_active_by_payload);
component.pilot_values = complexDoubleSha256( ...
    artifacts.pilot_values_active_by_payload);
semanticText = sprintf([ ...
    'bistatic_t01_artifact_semantic_v1|class=%s|production=%d|' ...
    'resolved_by=%s|config_sha256=%s|preamble_fd=%s|' ...
    'pilot_mask=%s|pilot_values=%s'], ...
    artifactClass, double(artifacts.production_allowed), resolvedBy, ...
    configSha256, component.preamble_fd, component.pilot_mask, ...
    component.pilot_values);

identity.semantic_sha256 = bistatic_sha256(semanticText, false);
identity.component_sha256 = component;
identity.serialization = [ ...
    'bistatic_t01_artifact_semantic_v1 over artifact identity and three ' ...
    'ordered component hashes; numeric arrays use schema/shape UTF-8 ' ...
    'headers and MATLAB-column-major IEEE-754 binary64 little-endian planes'];
end

function digest = complexDoubleSha256(values)
dimensionText = sprintf('%d,', size(values));
dimensionText(end) = [];
header = sprintf([ ...
    'bistatic_complex_double_sha256_v1|ndims=%d|size=%s|' ...
    'order=MATLAB_column_major|layout=real_plane_then_imag_plane|' ...
    'encoding=IEEE754_binary64_little_endian|'], ...
    ndims(values), dimensionText);
payload = [uint8(unicode2native(header, 'UTF-8')).'; ...
    binary64LittleEndian(real(values)); ...
    binary64LittleEndian(imag(values))];
digest = bistatic_sha256(payload, false);
end

function digest = logicalArraySha256(values)
dimensionText = sprintf('%d,', size(values));
dimensionText(end) = [];
header = sprintf([ ...
    'bistatic_logical_sha256_v1|ndims=%d|size=%s|' ...
    'order=MATLAB_column_major|encoding=uint8_0_or_1|'], ...
    ndims(values), dimensionText);
payload = [uint8(unicode2native(header, 'UTF-8')).'; uint8(values(:))];
digest = bistatic_sha256(payload, false);
end

function bytes = binary64LittleEndian(values)
bytes = reshape(typecast(double(values(:)), 'uint8'), 8, []);
[~, ~, endian] = computer;
if endian == 'B'
    bytes = flipud(bytes);
end
bytes = bytes(:);
end

function value = sha256Text(value, label)
value = textScalar(value, label);
if numel(value) ~= 64 || ...
        ~all(ismember(value, '0123456789abcdef'))
    error('bistatic:ArtifactContentIdentitySha256', ...
        '%s must be a lowercase 64-digit SHA-256 value.', label);
end
end

function value = textScalar(value, label)
if isstring(value)
    if ~isscalar(value) || ismissing(value)
        error('bistatic:ArtifactContentIdentityText', ...
            '%s must be a nonmissing text scalar.', label);
    end
    value = char(value);
elseif ~ischar(value) || ~isrow(value) || isempty(value)
    error('bistatic:ArtifactContentIdentityText', ...
        '%s must be a nonempty character row or string scalar.', label);
end
end
