-- V5.1 Sync_OTA: every output_valid beat transfers at clk150.
-- No output ready or intermediate DDR interface. All clocks run during reset.
-- stream_first/last mark independent input segments, not algorithm frames.
-- See docs/v51/INTERFACE_CONTRACT_ZH.md. Generated by tools/v51/wrapper_interface.py.
library ieee;
use ieee.std_logic_1164.all;
entity sync_ota_wrapper is
  port(
    clk125 : in std_logic;
    clk150 : in std_logic;
    clk500 : in std_logic;
    reset_request : in std_logic;
    cancel : in std_logic;
    stream_valid : in std_logic;
    stream_ready : out std_logic;
    stream_data : in std_logic_vector(127 downto 0);
    stream_first : in std_logic;
    stream_last : in std_logic;
    read_done : in std_logic;
    output_valid : out std_logic;
    output_data : out std_logic_vector(127 downto 0);
    output_frame : out std_logic_vector(31 downto 0);
    output_generation : out std_logic_vector(31 downto 0);
    output_beat : out std_logic_vector(31 downto 0);
    output_last : out std_logic;
    busy125 : out std_logic;
    fault125 : out std_logic;
    error125 : out std_logic_vector(7 downto 0);
    ingress_stage125 : out std_logic_vector(2 downto 0);
    accepted_words125 : out std_logic_vector(63 downto 0);
    frames_created125 : out std_logic_vector(31 downto 0);
    segments_started125 : out std_logic_vector(31 downto 0);
    segments_completed125 : out std_logic_vector(31 downto 0);
    frame_done125 : out std_logic;
    done_frame125 : out std_logic_vector(31 downto 0);
    done_generation125 : out std_logic_vector(31 downto 0);
    completed_frames125 : out std_logic_vector(31 downto 0);
    frontend_candidates125 : out std_logic_vector(31 downto 0);
    frontend_rejected125 : out std_logic_vector(31 downto 0);
    frontend_dropped125 : out std_logic_vector(31 downto 0);
    frontend_confirmed125 : out std_logic_vector(31 downto 0);
    frontend_error125 : out std_logic_vector(15 downto 0);
    sfo_error125 : out std_logic_vector(7 downto 0);
    sfo_error150 : out std_logic_vector(7 downto 0);
    context_error150 : out std_logic_vector(7 downto 0);
    cfo_error150 : out std_logic_vector(7 downto 0);
    coarse_beats150 : out std_logic_vector(31 downto 0);
    final_beats150 : out std_logic_vector(31 downto 0);
    coarse_saturations150 : out std_logic_vector(31 downto 0);
    final_saturations150 : out std_logic_vector(31 downto 0);
    cfo_window_words150 : out std_logic_vector(12 downto 0);
    cfo_windows150 : out std_logic_vector(6 downto 0);
    cfo_result150 : out std_logic_vector(498 downto 0);
    sfo_diagnostic150 : out std_logic_vector(255 downto 0)
  );
end entity;
architecture rtl of sync_ota_wrapper is
  component sync_ota_top is
    port(
    clk125 : in std_logic;
    clk150 : in std_logic;
    clk500 : in std_logic;
    reset_request : in std_logic;
    cancel : in std_logic;
    stream_valid : in std_logic;
    stream_ready : out std_logic;
    stream_data : in std_logic_vector(127 downto 0);
    stream_first : in std_logic;
    stream_last : in std_logic;
    read_done : in std_logic;
    output_valid : out std_logic;
    output_data : out std_logic_vector(127 downto 0);
    output_frame : out std_logic_vector(31 downto 0);
    output_generation : out std_logic_vector(31 downto 0);
    output_beat : out std_logic_vector(31 downto 0);
    output_last : out std_logic;
    busy125 : out std_logic;
    fault125 : out std_logic;
    error125 : out std_logic_vector(7 downto 0);
    ingress_stage125 : out std_logic_vector(2 downto 0);
    accepted_words125 : out std_logic_vector(63 downto 0);
    frames_created125 : out std_logic_vector(31 downto 0);
    segments_started125 : out std_logic_vector(31 downto 0);
    segments_completed125 : out std_logic_vector(31 downto 0);
    frame_done125 : out std_logic;
    done_frame125 : out std_logic_vector(31 downto 0);
    done_generation125 : out std_logic_vector(31 downto 0);
    completed_frames125 : out std_logic_vector(31 downto 0);
    frontend_candidates125 : out std_logic_vector(31 downto 0);
    frontend_rejected125 : out std_logic_vector(31 downto 0);
    frontend_dropped125 : out std_logic_vector(31 downto 0);
    frontend_confirmed125 : out std_logic_vector(31 downto 0);
    frontend_error125 : out std_logic_vector(15 downto 0);
    sfo_error125 : out std_logic_vector(7 downto 0);
    sfo_error150 : out std_logic_vector(7 downto 0);
    context_error150 : out std_logic_vector(7 downto 0);
    cfo_error150 : out std_logic_vector(7 downto 0);
    coarse_beats150 : out std_logic_vector(31 downto 0);
    final_beats150 : out std_logic_vector(31 downto 0);
    coarse_saturations150 : out std_logic_vector(31 downto 0);
    final_saturations150 : out std_logic_vector(31 downto 0);
    cfo_window_words150 : out std_logic_vector(12 downto 0);
    cfo_windows150 : out std_logic_vector(6 downto 0);
    cfo_result150 : out std_logic_vector(498 downto 0);
    sfo_diagnostic150 : out std_logic_vector(255 downto 0)
    );
  end component;
begin
  core : sync_ota_top
    port map(
      clk125 => clk125,
      clk150 => clk150,
      clk500 => clk500,
      reset_request => reset_request,
      cancel => cancel,
      stream_valid => stream_valid,
      stream_ready => stream_ready,
      stream_data => stream_data,
      stream_first => stream_first,
      stream_last => stream_last,
      read_done => read_done,
      output_valid => output_valid,
      output_data => output_data,
      output_frame => output_frame,
      output_generation => output_generation,
      output_beat => output_beat,
      output_last => output_last,
      busy125 => busy125,
      fault125 => fault125,
      error125 => error125,
      ingress_stage125 => ingress_stage125,
      accepted_words125 => accepted_words125,
      frames_created125 => frames_created125,
      segments_started125 => segments_started125,
      segments_completed125 => segments_completed125,
      frame_done125 => frame_done125,
      done_frame125 => done_frame125,
      done_generation125 => done_generation125,
      completed_frames125 => completed_frames125,
      frontend_candidates125 => frontend_candidates125,
      frontend_rejected125 => frontend_rejected125,
      frontend_dropped125 => frontend_dropped125,
      frontend_confirmed125 => frontend_confirmed125,
      frontend_error125 => frontend_error125,
      sfo_error125 => sfo_error125,
      sfo_error150 => sfo_error150,
      context_error150 => context_error150,
      cfo_error150 => cfo_error150,
      coarse_beats150 => coarse_beats150,
      final_beats150 => final_beats150,
      coarse_saturations150 => coarse_saturations150,
      final_saturations150 => final_saturations150,
      cfo_window_words150 => cfo_window_words150,
      cfo_windows150 => cfo_windows150,
      cfo_result150 => cfo_result150,
      sfo_diagnostic150 => sfo_diagnostic150
    );
end architecture;
