
####################################################################################
# Generated by Vivado 2021.1 built on 'Thu Jun 10 19:36:33 MDT 2021' by 'xbuild'
# Command Used: write_xdc -force D:/008_MA_Dev/Sync_Frontend/work/SF003_DCP_check_20260914T223135Z/core_export_constraints.xdc
####################################################################################


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
