@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Sep 17 20:47:38 +0200 2026
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 5fb2d32ab3a94f3fa7f431bba8706f84 --incr --debug typical --relax --mt 16 -L xil_defaultlib -L secureip --snapshot tb_ddr_capture_ctrl_behav xil_defaultlib.tb_ddr_capture_ctrl -log elaborate.log"
call xelab  -wto 5fb2d32ab3a94f3fa7f431bba8706f84 --incr --debug typical --relax --mt 16 -L xil_defaultlib -L secureip --snapshot tb_ddr_capture_ctrl_behav xil_defaultlib.tb_ddr_capture_ctrl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
