#!/usr/bin/env python3
"""CFO-PHASE004 wrapper-only repair: reuse a verified create checkpoint and run simulate."""
from __future__ import annotations
import argparse, datetime as dt, importlib.util, json, os
from pathlib import Path

if os.name != "nt": raise SystemExit("Windows only")
ROOT=Path(r"D:\008_MA_Dev\T11_CFO"); GUARD=ROOT/"tools/cfo_phase74_guard_v1.py"
sp=importlib.util.spec_from_file_location("cfo_phase74_guard_v1",GUARD); assert sp and sp.loader
Q=importlib.util.module_from_spec(sp); sp.loader.exec_module(Q)
SIM=300; ZERO=5

def checkpoint(prior):
    completion_path=prior/"ATTEMPT_COMPLETION.json"; freeze_path=prior/"EXECUTION_FREEZE.json"; samples_path=prior/"create.samples.jsonl"
    c=json.loads(completion_path.read_text(encoding="utf-8")); s=c["stages"]["create"]; rows=[json.loads(x) for x in samples_path.read_text(encoding="utf-8-sig").splitlines() if x.strip()]
    ready_pid=s.get("ready_pid"); ready_rows=[x for x in rows if x.get("ready_pid")==ready_pid]
    telemetry_ok=bool(rows and all(x.get("job_pid_cross_check",{}).get("match") is True and not x.get("job_census_issues") and not x.get("job_census_error") and not x.get("job_process_open_failures") for x in rows) and any(any(int(t.get("pid",-1))==int(ready_pid) and t.get("private_usage_bytes") is not None for t in x.get("active_process_tree",[])) for x in ready_rows))
    stored=s.get("verify",{}); current=Q.py(Q.VP,"--sources",prior/"create_actual_sources.csv","--identity",prior/"create_project_identity.txt"); xpr=Q.info(Q.XPR); stored_xpr=s.get("xpr",{})
    checks={"prior_status_blocked_after_create":c.get("status")=="BLOCKED_AFTER_CREATE","binding_succeeded":s.get("binding_succeeded") is True,"native_exit_zero":s.get("native_exit_code_final")==0,"native_not_terminated":s.get("termination_requested_by_controller") is False,"native_markers":s.get("markers",{}).get("ready",{}).get("found") is True and s.get("markers",{}).get("done",{}).get("found") is True,"native_zero_verified":s.get("final_census_before_close",{}).get("empty_verified") is True,"no_controller_errors":not s.get("controller_errors"),"no_persistent_telemetry_fault":s.get("persistent_telemetry_fault") is False,"telemetry_samples_valid":telemetry_ok,"stored_verify_exit_zero":stored.get("exit_code")==0,"rechecked_verify_exit_zero":current.get("exit_code")==0,"xpr_exists":xpr.get("exists") is True,"xpr_matches_create_checkpoint":xpr.get("sha256")==stored_xpr.get("sha256")}
    return {"checks":checks,"all_checks":all(checks.values()),"prior_completion":{"path":str(completion_path),"info":Q.info(completion_path)},"prior_freeze":{"path":str(freeze_path),"info":Q.info(freeze_path)},"prior_stage":s,"sample_count":len(rows),"ready_sample_count":len(ready_rows),"stored_verify":stored,"rechecked_verify":current,"current_xpr":xpr,"stored_xpr":stored_xpr}

def command(stage,attempt):
    return [str(Q.VIVADO),"-mode","batch","-source","D:/008_MA_Dev/T11_CFO/vivado/phase74_project.tcl","-log",str(attempt/f"{stage}.log"),"-journal",str(attempt/f"{stage}.jou"),"-tclargs",stage,str(attempt)]
def sim_pass(r):
    m=r.get("markers",{}); f=r.get("final_census_before_close",{}); v=Q.pass_values(m.get("passed",{})); r["raw_pass_values"]=v
    common=bool(r.get("binding_succeeded") and r.get("events",{}).get("zero") and f.get("empty_verified") and r.get("native_exit_code_final")==0 and not r.get("controller_errors") and not r.get("persistent_telemetry_fault") and not r.get("termination_requested_by_controller") and m.get("ready",{}).get("found") and m.get("done",{}).get("found") and r.get("ready_pid",0)>0 and r.get("stable_telemetry_samples",0)>=1 and r.get("unstable_after_ready_samples",0)<=3)
    return bool(common and m.get("passed",{}).get("found") and v and v["unique"]==27 and v["completed"]==33 and v["protocol_errors"]==5 and v["stalled_cycles"]==150 and v["reset_discards"]==3 and v["abort_discards"]==3 and v["max_tail"]<=6000 and v["max_total"]<=11000)
def freeze(root,attempt,cp,pre,base,mem,lock,rows,lockok):
    checks={"source_lock_hash":Q.info(Q.LOCK).get("sha256")==Q.LOCK_SHA,"all_25_locked_files_match":lockok and len(rows)==25,"old_sync_xpr_expected":Q.info(Q.OLD_SYNC).get("sha256")==Q.SYNC_SHA,"old_coord_xpr_expected":Q.info(Q.OLD_COORD).get("sha256")==Q.COORD_SHA,"create_checkpoint_valid":cp["all_checks"],"phase_xpr_matches_checkpoint":cp["current_xpr"].get("sha256")==cp["stored_xpr"].get("sha256"),"preflight_rotator_exit_0":pre["rotator"]["exit_code"]==0,"preflight_coordinate_exit_0":pre["coordinate"]["exit_code"]==0,"preflight_phase74_exit_0":pre["phase74"]["exit_code"]==0,"t10_vivado_present":any(int(x.get("pid",-1))==34768 and str(x.get("image_name","")).lower()=="vivado.exe" for x in base["all_native_processes"]),"t10_xsim_present":any(int(x.get("pid",-1))==28856 and str(x.get("image_name","")).lower()=="xsimk.exe" for x in base["all_native_processes"]),"no_other_vivado_or_xsim_process":not base["non_reserved_native_processes"],"free_memory_recommendation":isinstance(mem.get("available_physical_bytes"),int) and mem["available_physical_bytes"]>=Q.FREE}
    cmds={k:command(k,attempt) for k in ("create","simulate")}
    return {"schema":"cfo_phase004_resume_execution_freeze_v1","job_id":"CFO-PHASE004","recorded_utc":Q.utc(),"root":str(root),"attempt":str(attempt),"repair_kind":"wrapper_only_false_negative_checkpoint_reuse","controller":{"path":str(Path(__file__).resolve()),"info":Q.info(Path(__file__).resolve()),"original_controller":{"path":str(GUARD),"info":Q.info(GUARD)}},"reused_create_checkpoint":cp,"source_lock":{"path":str(Q.LOCK),"expected_sha256":Q.LOCK_SHA,"actual":Q.info(Q.LOCK),"members":rows,"member_count":len(rows),"all_members_match":lockok,"project_members":lock["project_members"]},"frozen_project":{"part":lock["part"],"hardware_top":lock["hardware_top"],"simulation_top":lock["simulation_top"],"new_xpr":str(Q.XPR),"new_xpr_preexisting":True,"old_sync_xpr":Q.info(Q.OLD_SYNC),"old_coord_xpr":Q.info(Q.OLD_COORD)},"dependencies":{str(p):Q.info(p) for p in [Q.DOC,Q.CONTRACT,Q.VP,Q.VC,Q.VR,Q.TCL,Q.THREADS,Q.CONFIG,Q.OLD_SYNC,Q.OLD_COORD]},"tools":{"python":str(Q.PYTHON),"python_version":__import__("sys").version,"vivado":str(Q.VIVADO),"vivado_version_declared":"2021.1"},"preflight_verification":pre,"preexisting_native_processes":base,"startup_memory":mem,"resources":{"t10_reserved_pids":Q.T10,"max_concurrent_cfo_vivado":1,"matlab_slots":0,"planned_peak_gib_warning":4,"free_recommendation_gib":6,"hard_memory_available_gib":.25,"sustained_memory_available_gib":.5,"sustained_memory_seconds":30,"native_stages_serial":True,"xelab_jobs":16,"general_maxThreads":8,"synth_maxThreads":8},"commands":cmds,"hard_timeouts_seconds":{"simulate":SIM,"post_trigger_zero_grace":ZERO},"scope_guards":{"no_t10_operation":True,"no_matlab":True,"no_old_runner":True,"no_create_rerun":True,"no_normal_error_hold_repeat":True,"no_rotator_repeat":True,"no_coordinate_repeat":True,"no_synthesis":True,"no_implementation":True,"no_fft_or_fullframe":True,"no_auto_restart":True,"no_native_started_before_freeze":True},"checks":checks}
def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--prior-create-attempt",type=Path,required=True); q=ap.parse_args(); root=ROOT.resolve(); prior=q.prior_create_attempt.resolve()
    parent=root/"work/CFO_PHASE004"; parent.mkdir(parents=True,exist_ok=True); a=parent/f"attempt_{dt.datetime.now(dt.timezone.utc).strftime('%Y%m%dT%H%M%S%fZ')}_luna_resume"; a.mkdir(); ep=a/"controller_events.jsonl"; Q.wjson(a/"report_clock.json",{"schema":"cfo_phase004_resume_report_clock_v1","thread_id":"01a076f0-d8c0-72a0-8371-cb2ff29c1b28","started_utc":Q.utc(),"interval_minutes":15,"status":"ACTIVE"})
    cp=checkpoint(prior); pre={"rotator":Q.py(Q.VR),"coordinate":Q.py(Q.VC),"phase74":Q.py(Q.VP)}; base=Q.baseline(); mem=Q.G.mem(); lock,rows,lockok=Q.locked(root); fr=freeze(root,a,cp,pre,base,mem,lock,rows,lockok); fsha=Q.wjson(a/"EXECUTION_FREEZE.json",fr); Q.event(ep,"execution_freeze_written",sha256=fsha,checks=fr["checks"])
    if not all(fr["checks"].values()):
        c={"schema":"cfo_phase004_completion_v1","job_id":"CFO-PHASE004","status":"BLOCKED_RESUME_PREFLIGHT","attempt":str(a),"execution_freeze":{"path":str(a/"EXECUTION_FREEZE.json"),"sha256":fsha},"checks":fr["checks"],"scope_guards":fr["scope_guards"],"post_native_processes":Q.G.native_snapshot(),"repair_audit":{"original_attempt":str(prior),"native_create_repeated":False}}; ch,mh=Q.complete(a,root,c); print(json.dumps({"status":c["status"],"attempt":str(a),"completion_sha256":ch,"manifest_sha256":mh})); return 3
    Q.wjson(a/"create_checkpoint_reuse.json",cp); sim=Q.stage(root,a,"simulate",fr["commands"]["simulate"],SIM,ep); sim["verify"]=Q.py(Q.VP,"--actual",a/"phase74_actual.txt","--sources",a/"simulate_actual_sources.csv","--identity",a/"simulate_project_identity.txt")
    try: sim["verify_json"]=json.loads([x for x in sim["verify"]["stdout"].splitlines() if x.strip()][-1])
    except Exception: sim["verify_json"]=None
    sim["xpr"]=Q.info(Q.XPR); sim["status"]="PASS" if sim_pass(sim) and sim["verify"]["exit_code"]==0 else "FAIL"; Q.wjson(a/"simulate_verify.json",sim["verify"])
    xa={"schema":"cfo_phase004_xpr_audit_v1","reused_create_xpr":cp["stored_xpr"],"final_xpr":sim["xpr"],"sha256_unchanged":cp["stored_xpr"].get("sha256")==sim["xpr"].get("sha256")}; xsha=Q.wjson(a/"FINAL_XPR_AUDIT.json",xa); post=Q.G.native_snapshot(); tgood,tdelta=Q.t10_ok(base,{"all_native_processes":post}); pl,pm,pok=Q.locked(root); status="PASS" if sim["status"]=="PASS" and tgood and pok else "FAIL"
    c={"schema":"cfo_phase004_completion_v1","job_id":"CFO-PHASE004","status":status,"attempt":str(a),"generated_utc":Q.utc(),"execution_freeze":{"path":str(a/"EXECUTION_FREEZE.json"),"sha256":fsha},"stages":{"create":{"status":"PASS_REUSED_CHECKPOINT","attempt":str(prior),"checkpoint_validation":cp},"simulate":sim},"final_xpr_audit":{"path":str(a/"FINAL_XPR_AUDIT.json"),"sha256":xsha,**xa},"post_source_lock":{"lock":pl,"members":pm,"all_members_match":pok},"post_native_processes":post,"t10_unchanged":tdelta,"t10_not_operated_by_controller":True,"no_matlab":True,"no_old_runner":True,"no_create_rerun":True,"no_synthesis_or_implementation":True,"scope":"Wrapper-only repair reused the independently verified create checkpoint and ran only the authorized serial behavioral simulate stage; no create rerun, FFT, full-frame, T11/T12/T13, synthesis, timing, or 500MS/s claim.","repair_audit":{"kind":"wrapper_only_false_negative","original_attempt":str(prior),"original_controller":{"path":str(GUARD),"info":Q.info(GUARD)},"repaired_controller":{"path":str(Path(__file__).resolve()),"info":Q.info(Path(__file__).resolve())},"reason":"A single valid post-READY telemetry sample was sufficient for the short native create stage; original wrapper required two and sealed a false negative.","native_create_repeated":False,"rtl_or_vector_modified":False}}; ch,mh=Q.complete(a,root,c); print(json.dumps({"status":status,"attempt":str(a),"completion_sha256":ch,"manifest_sha256":mh})); return 0 if status=="PASS" else 6
if __name__=="__main__": raise SystemExit(main())
