# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/008_MA_Dev/Sync_OTA/Sync_OTA.runs/synth_1/sync_ota_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcvu11p-flgb2104-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/008_MA_Dev/Sync_OTA/Sync_OTA.cache/wt [current_project]
set_property parent.project_path D:/008_MA_Dev/Sync_OTA/Sync_OTA.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib ota_xpm [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/008_MA_Dev/Sync_OTA/Sync_OTA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs D:/008_MA_Dev/Sync_OTA/rtl/include [current_fileset]
set src_rc [catch { 
  puts "source D:/008_MA_Dev/Sync_OTA/tools/vivado/run_threads.tcl"
  source D:/008_MA_Dev/Sync_OTA/tools/vivado/run_threads.tcl
} _RESULT] 
if {$src_rc} { 
  send_msg_id runtcl-1 status "$_RESULT"
  send_msg_id runtcl-2 status "sourcing script D:/008_MA_Dev/Sync_OTA/tools/vivado/run_threads.tcl failed"
  return -code error
}
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  D:/008_MA_Dev/Sync_OTA/rtl/include/initial_observation_ip_config.svh
  D:/008_MA_Dev/Sync_OTA/rtl/include/initial_pair_max_tracker_ip_config.svh
  D:/008_MA_Dev/Sync_OTA/rtl/include/initial_shared_gain_ip_config.svh
}
set_property file_type "Verilog Header" [get_files D:/008_MA_Dev/Sync_OTA/rtl/include/initial_observation_ip_config.svh]
set_property file_type "Verilog Header" [get_files D:/008_MA_Dev/Sync_OTA/rtl/include/initial_pair_max_tracker_ip_config.svh]
set_property file_type "Verilog Header" [get_files D:/008_MA_Dev/Sync_OTA/rtl/include/initial_shared_gain_ip_config.svh]
read_mem {
  D:/008_MA_Dev/Sync_OTA/ip/rom/fine_ps1_reference_16lane.mem
  D:/008_MA_Dev/Sync_OTA/ip/rom/residual_pilot_phase.mem
  D:/008_MA_Dev/Sync_OTA/ip/cfo/cfo_rot_lut.mem
  D:/008_MA_Dev/Sync_OTA/ip/cfo/fft2048_twiddle.mem
  D:/008_MA_Dev/Sync_OTA/ip/cfo/front2048_coefficient_index.mem
  D:/008_MA_Dev/Sync_OTA/ip/cfo/front2048_coefficient_page0.mem
  D:/008_MA_Dev/Sync_OTA/ip/cfo/front2048_coefficient_page1.mem
  D:/008_MA_Dev/Sync_OTA/ip/cfo/front2048_coefficient_table.mem
  D:/008_MA_Dev/Sync_OTA/ip/cfo/fft256_twiddle.mem
  D:/008_MA_Dev/Sync_OTA/ip/cfo/phase74_atan_q31.mem
}
read_verilog -library ota_xpm -sv {
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/common/bistatic_stream_pkg.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/carrier/cfo_coarse_estimator.sv
  D:/008_MA_Dev/Sync_OTA/rtl/cfo/cfo_coordinate_control.sv
  D:/008_MA_Dev/Sync_OTA/rtl/cfo/cfo_divide_rne64.sv
  D:/008_MA_Dev/Sync_OTA/rtl/cfo/cfo_divide_rne64wide.sv
  D:/008_MA_Dev/Sync_OTA/rtl/cfo/cfo_estimate74_backend_a07.sv
  D:/008_MA_Dev/Sync_OTA/rtl/cfo/cfo_estimator_link_a06.sv
  D:/008_MA_Dev/Sync_OTA/rtl/cfo/cfo_fft2048_core.sv
  D:/008_MA_Dev/Sync_OTA/rtl/cfo/cfo_fft256_core.sv
  D:/008_MA_Dev/Sync_OTA/rtl/cfo/cfo_fft74_quality_v2.sv
  D:/008_MA_Dev/Sync_OTA/rtl/cfo/cfo_front2048_window_a07.sv
  D:/008_MA_Dev/Sync_OTA/rtl/cfo/cfo_phase74_core_v2.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/carrier/cfo_phase_increment.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/carrier/cfo_preamble_rotator.sv
  D:/008_MA_Dev/Sync_OTA/rtl/cfo/cfo_rotate4.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/coarse_corr_energy_4lane.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/buffering/coarse_lag1024_beat_ring.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/coarse_metric_threshold.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/coarse_plateau_selector.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/buffering/coarse_result_pair_fifo.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/coarse_rolling_sc_accumulator.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/coarse_safe_phase_replay.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/fine_corr_accumulator.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/fine_corr_cmpy_array.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/fine_corr_metric_controller.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/fine_corr_scheduler.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/buffering/fine_corrected_local_buffer.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/buffering/fine_energy_prefix_buffer.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/buffering/fine_local_capture_buffer.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/fine_local_window_reader.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/fine_partitioned_corr_engine.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/fine_peak_selector.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/fine_ps1_reference_rom.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/fine_quality_controller.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/fine_quality_vendor_adapters.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/fine_vendor_multiplier_adapters.sv
  D:/008_MA_Dev/Sync_OTA/rtl/common/ota_async_fifo_a06.sv
  D:/008_MA_Dev/Sync_OTA/rtl/cfo/ota_cfo_chain_onchip.sv
  D:/008_MA_Dev/Sync_OTA/rtl/buffer/ota_cfo_window_queue.sv
  D:/008_MA_Dev/Sync_OTA/rtl/control/ota_raw_lease_scheduler.sv
  D:/008_MA_Dev/Sync_OTA/rtl/buffer/ota_raw_training_hub.sv
  D:/008_MA_Dev/Sync_OTA/rtl/control/ota_sfo_context_join.sv
  D:/008_MA_Dev/Sync_OTA/rtl/buffer/ota_shared_raw_store.sv
  D:/008_MA_Dev/Sync_OTA/rtl/control/ota_stream_ingress.sv
  D:/008_MA_Dev/Sync_OTA/rtl/control/ota_training_dispatch.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_cfo_phase_increment.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/control/sfo_domain_reset.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/resampling/sfo_farrow_arithmetic.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/resampling/sfo_fir_down15.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/resampling/sfo_fir_down47.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/resampling/sfo_fir_up15.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/resampling/sfo_fir_up47.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/first_resampling/sfo_first_frame_scheduler.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/first_resampling/sfo_first_pass_descriptor.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/first_resampling/sfo_first_resampler.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/resampling/sfo_guarded_farrow_stream.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/resampling/sfo_guarded_resampling_core.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_cfo_derotate_s16_4lane.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_dds_phase_4lane.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_derotate_wide_4lane.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/common/sfo_stream_pkg.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_estimation_service.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_estimator.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/fft_service/sfo_initial_fft_arbiter.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_fft_pair_extractor.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_fft_pair_extractor_fifo.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_fft_pair_extractor_memory.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/fft_service/sfo_initial_fft_service.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_fft_swls_backend.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_five_sum_accumulator.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_frame_context_join.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_observation_engine.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_observation_engine_2lane.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_observation_engine_fifo.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_observation_store.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_observation_store_bank.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_pair_max_tracker_2lane.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_pair_phasor_bfp.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_ps3_ps10_job_sequencer.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_raw_reader_4lane.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_raw_reader_local_capture.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_raw_to_fft_frontend.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_regression_tail.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_shared_gain_s16_4lane.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_shared_gain_s16_lane.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_swls_weighted_backend.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_unsigned_divider_service.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_unsigned_divider_service_fifo.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/initial_estimation/sfo_initial_weight_pack.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/buffering/sfo_intermediate_frame_bank.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/resampling/sfo_nominal_pack4.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/buffering/sfo_output_buffer.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/buffering/sfo_raw_frame_ring.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/buffering/sfo_record_cdc_fifo.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/residual_estimation/sfo_residual_delay_backend4.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/residual_estimation/sfo_residual_div_u80_u49_rne.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/residual_estimation/sfo_residual_estimator4.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/residual_estimation/sfo_residual_fft_grid_stage4.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/fft_service/sfo_residual_fft_service4.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/fft_service/sfo_residual_fft_window4.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/residual_estimation/sfo_residual_grid_packet_queue2.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/fft_service/sfo_residual_ifft_service4.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/residual_estimation/sfo_residual_ls74.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/residual_estimation/sfo_residual_nominal_window_reader4.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/residual_estimation/sfo_residual_peak_interpolate.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/residual_estimation/sfo_residual_peak_triplet4.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/residual_estimation/sfo_residual_pilot_front2.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/residual_estimation/sfo_residual_pilot_grid4.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/residual_estimation/sfo_residual_pilot_rotate2.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/residual_estimation/sfo_residual_pilot_select_phase4.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/residual_estimation/sfo_residual_power4.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/second_resampling/sfo_second_pass_descriptor.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/second_resampling/sfo_second_resampler.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/buffering/sfo_sync_fifo.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/buffering/sfo_training_capture_buffer.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/control/sfo_two_pass_transport.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/buffering/sfo_uram_frame_bank.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/common/sfo_vendor_multiplier_adapters.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/buffering/sync_beat_ram.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/frontend/sync_coarse_pair_join.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/frontend/sync_continuous_detector.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/frontend/sync_frontend_top.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/sync_rolling_metric.sv
  D:/008_MA_Dev/Sync_OTA/rtl/sfo/control/sync_sfo_top.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/to_coarse_estimator.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/to_fine_core.sv
  D:/008_MA_Dev/Sync_OTA/rtl/frontend/timing/to_fine_estimator.sv
  D:/008_MA_Dev/Sync_OTA/rtl/control/sync_ota_top_v51.sv
}
read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/farrow_add_18/farrow_add_18.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/farrow_add_18/farrow_add_18_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/farrow_add_28/farrow_add_28.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/farrow_add_28/farrow_add_28_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/farrow_add_32/farrow_add_32.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/farrow_add_32/farrow_add_32_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/farrow_mul_h16/farrow_mul_h16.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/farrow_mul_h16/farrow_mul_h16_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/farrow_mul_t16/farrow_mul_t16.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/farrow_mul_t16/farrow_mul_t16_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t03_xfft_16384_aux/t03_xfft_16384_aux.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t03_xfft_16384_aux/t03_xfft_16384_aux_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t03_xfft_2048_main/t03_xfft_2048_main.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t03_xfft_2048_main/t03_xfft_2048_main_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t04_cmpy_17x16/t04_cmpy_17x16.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t04_cmpy_17x16/t04_cmpy_17x16_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t04_cordic_translate_48/t04_cordic_translate_48.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t04_cordic_translate_48/t04_cordic_translate_48_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t04_div_u63_u47/t04_div_u63_u47.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t04_div_u63_u47/t04_div_u63_u47_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t04_phase_scale_s48_x_1953125/t04_phase_scale_s48_x_1953125.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t04_phase_scale_s48_x_1953125/t04_phase_scale_s48_x_1953125_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t04_square_s43/t04_square_s43.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t04_square_s43/t04_square_s43_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t04_square_u42/t04_square_u42.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t04_square_u42/t04_square_u42_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_cmpy_corr_18x16/t05_cmpy_corr_18x16.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_cmpy_corr_18x16/t05_cmpy_corr_18x16_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_cmpy_rotate_18x18/t05_cmpy_rotate_18x18.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_cmpy_rotate_18x18/t05_cmpy_rotate_18x18_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_dds_pinc32_sincos18/t05_dds_pinc32_sincos18.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_dds_pinc32_sincos18/t05_dds_pinc32_sincos18_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_div_quality_s64_s64_f15/t05_div_quality_s64_s64_f15.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_div_quality_s64_s64_f15/t05_div_quality_s64_s64_f15_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_mult_cfo_s19_const40_full59/t05_mult_cfo_s19_const40_full59.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_mult_cfo_s19_const40_full59/t05_mult_cfo_s19_const40_full59_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_mult_quality_u46x36_full82/t05_mult_quality_u46x36_full82.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_mult_quality_u46x36_full82/t05_mult_quality_u46x36_full82_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_mult_s18x18_full36/t05_mult_s18x18_full36.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_mult_s18x18_full36/t05_mult_s18x18_full36_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_mult_s48x48_full96/t05_mult_s48x48_full96.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t05_mult_s48x48_full96/t05_mult_s48x48_full96_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_cordic_translate48_parallel/t06_cordic_translate48_parallel.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_cordic_translate48_parallel/t06_cordic_translate48_parallel_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_dds_phase_s32_sincos18/t06_dds_phase_s32_sincos18.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_dds_phase_s32_sincos18/t06_dds_phase_s32_sincos18_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_fs_mult_s29_s11/t06_fs_mult_s29_s11.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_fs_mult_s29_s11/t06_fs_mult_s29_s11_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_fs_mult_s29_s48/t06_fs_mult_s29_s48.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_fs_mult_s29_s48/t06_fs_mult_s29_s48_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_fs_mult_u18_s11/t06_fs_mult_u18_s11.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_fs_mult_u18_s11/t06_fs_mult_u18_s11_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_fs_mult_u18_s48/t06_fs_mult_u18_s48.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_fs_mult_u18_s48/t06_fs_mult_u18_s48_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_observation_engine_square/t06_observation_engine_square.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_observation_engine_square/t06_observation_engine_square_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_observation_engine_weight_product/t06_observation_engine_weight_product.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_observation_engine_weight_product/t06_observation_engine_weight_product_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_pair_max_tracker_2lane_cross/t06_pair_max_tracker_2lane_cross.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_pair_max_tracker_2lane_cross/t06_pair_max_tracker_2lane_cross_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_rt_mult_s41_s38/t06_rt_mult_s41_s38.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_rt_mult_s41_s38/t06_rt_mult_s41_s38_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_rt_mult_s41_s41/t06_rt_mult_s41_s41.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_rt_mult_s41_s41/t06_rt_mult_s41_s41_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_rt_mult_s41_u38/t06_rt_mult_s41_u38.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_rt_mult_s41_u38/t06_rt_mult_s41_u38_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_rt_mult_u30_s42/t06_rt_mult_u30_s42.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_rt_mult_u30_s42/t06_rt_mult_u30_s42_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_rt_mult_u30_u43/t06_rt_mult_u30_u43.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_rt_mult_u30_u43/t06_rt_mult_u30_u43_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_rt_mult_u30_u48/t06_rt_mult_u30_u48.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_rt_mult_u30_u48/t06_rt_mult_u30_u48_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_rt_mult_u48_u20/t06_rt_mult_u48_u20.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_rt_mult_u48_u20/t06_rt_mult_u48_u20_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_sg_div_u53_u37/t06_sg_div_u53_u37.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_sg_div_u53_u37/t06_sg_div_u53_u37_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_sg_mult_u37_u16/t06_sg_mult_u37_u16.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_sg_mult_u37_u16/t06_sg_mult_u37_u16_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_wp_mult_u64_u33/t06_wp_mult_u64_u33.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t06_wp_mult_u64_u33/t06_wp_mult_u64_u33_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t07_g3_down15/t07_g3_down15.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t07_g3_down15/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t07_g3_down15/t07_g3_down15_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t07_g3_down47/t07_g3_down47.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t07_g3_down47/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t07_g3_down47/t07_g3_down47_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t07_g3_up15/t07_g3_up15.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t07_g3_up15/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t07_g3_up15/t07_g3_up15_ooc.xdc]

read_ip -quiet D:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t07_g3_up47/t07_g3_up47.xci
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t07_g3_up47/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all d:/008_MA_Dev/Sync_OTA/Sync_OTA.srcs/sources_1/ip/t07_g3_up47/t07_g3_up47_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/008_MA_Dev/Sync_OTA/constraints/sync_ota_clocks.xdc
set_property used_in_implementation false [get_files D:/008_MA_Dev/Sync_OTA/constraints/sync_ota_clocks.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top sync_ota_top -part xcvu11p-flgb2104-2-e -flatten_hierarchy none -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sync_ota_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file sync_ota_top_utilization_synth.rpt -pb sync_ota_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
