from pathlib import Path
import json,hashlib,shutil,datetime,csv,zipfile,ast,sys
import numpy as np
R=Path(__file__).resolve().parents[2]
BASE=R/"reports/t09/design/T09_FIXED007";assert not BASE.exists()
PKG=BASE/"package";PKG.mkdir(parents=True)
OLD=R/"reports/t09/design/T09_STATS006/package"
STATS=R/"reports/t09/execution/T09_STATS006/attempt_20260908T223909180Z_luna"
records=[]
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest().upper()
def read(p):return json.loads(Path(p).read_text(encoding="utf-8-sig"))
def write(p,s):
    assert not p.exists(),p;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s,encoding="utf8")
def jsonfile(p,x):write(p,json.dumps(x,ensure_ascii=False,indent=2)+"\n")
def add(src,name):
    dst=PKG/name;assert not dst.exists();dst.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(src,dst)
    records.append(dict(path=name,source_path=str(src),sha256=sha(dst),bytes=dst.stat().st_size))
def generated(name):
    p=PKG/name;records.append(dict(path=name,source_path="generated by frozen builder; provenance included",sha256=sha(p),bytes=p.stat().st_size))
def rep(s,a,b):
    assert a in s,a[:90];return s.replace(a,b)
review="""# T09-STATS006：300个条件浮点输入的独立复核

结论为 ACCEPT_CONDITIONAL_FLOATING_STATISTICS_300_CASES，T09_PASS=false。23份冻结输入、627份结果哈希通过；独立重算22200个时域窗口FFT、600组延迟与最小二乘、60个10种子统计组。使用SciPy CZT独立重建无噪声窗口，再从保存窗口相减，核对噪声功率与LoS SNR定义；噪声功率最大相对差3.48e-12。没有重跑MATLAB发生器或统计。

| 方案 | 最差10种子组MAE / ppm | 最差单次绝对误差 / ppm | 全300输入MAE / ppm |
|---|---:|---:|---:|
| 2倍补零＋功率抛物线 | 0.01290637 | 0.03142455 | 0.00671995 |
| 4倍补零＋功率抛物线 | 0.01238962 | 0.02914176 | 0.00677644 |

全部60组均10/10有效且MAE<0.1ppm。在这个条件输入域中，4倍方案没有显示出值得立即增加IFFT长度的精度优势；先以2倍作为定点研究主候选，4倍保留为后备。这是工程选择，不表示更少补零在所有信道更优。

统计单元仍为每信道/SNR/残余/候选10种子；共享种子跨残余和SNR，不能算额外独立重复。理想Q28步长残余是速率公式，未执行第二遍重采样；不能当作300个实际T06/T08闭环。原CLOSED002/003真实输入结果及C10缺12尾样本、C11无效且削顶/饱和的边界继续保留。

原生MATLAB计算106.452秒；整个监督阶段125.198秒，根退出后5.0645秒自动清理，自有Job归零。Code Analyzer的MSNU仅是第48行过期NASGU抑制标记；保存原文件，未来修订删除标记，不因此重跑已完成统计。

详细独立证据：reports/t09/design/T09_STATS006/INDEPENDENT_REVIEW.json；脚本scripts/t09/review_t09_stats006.py。下一步只做有界官方FFT模型和逐运算定点研究；T09总验收仍等待定点、RTL、周期、时序及交付证据。
"""
reviewPath=R/"docs/t09/T09_STATS006_REVIEW_ZH.md";write(reviewPath,review)
plan="""# T09-FIXED007：官方FFT模型与逐运算定点小实验

目的：确认实际FFT缩放会保留多少精度，再决定RTL位宽。浮点统计已通过条件研究门；本包不重复生成波形，不启动新的MATLAB/Vivado，不宣布定点统计资格或T09 PASS。

## 先验证测量工具
调用本机Vivado2021.1自带xfft_v9_1_bitacc_cmodel_nt64.zip中的官方DLL。Python ctypes严格按随包头文件传值结构；I/Q输入预量化为S16并除32768，输出乘32768必须逐整数无小数。它是官方位精确模型；不以浮点fft后取整冒充IP整数结果。

先把主FFT已有XSim的job 0、7、355、711与原输入配对，四个2048窗口全部4096个I/Q整数逐个相等。再复用T03辅助FFT的8个ZERO/QUARTER_GRID_SPARSE_EXACT向量与权威PSF输出vn02，覆盖2048正、4096逆、8192正、16384逆。输入提取、父文件哈希、已有验收证据全部保存。不运行T06/T03 RTL。任何控制不一致即停止研究，Astra复核，不放宽为1LSB。

这8个辅助控制很稀疏，且没有2048逆方向。因此本包T09的2048逆变换只得到官方C模型结果，生产数据与实际XSim的匹配仍须下一阶段完成；不把这次工具复用说成已有RTL覆盖。

## 有界输入和比较
每例保留完整74窗口及真实17920采样的相邻导频时间，只有IFFT取2倍/2048点。
- 复用STATS006的case041论文15dB/+5ppm、091 TDL-D -5dB/+5ppm、271 TDL-D20dB/0ppm、291 TDL-D20dB/+5ppm，均用输入码比例32768；
- 另对相同case041增加比例263403的幅度对照。它只改变整数输入幅度，不重造信道/噪声，也不是独立随机种子；
- 复用真实第一遍输出frame6001、6006、6010、6011，保存窗口单位为S16码/32768，乘32768恢复已有整数，禁止另改增益或削顶。C10/C11压力与上游限制原样保留。
总9例×74窗口，两条分支为“导频后单位增益”和“导频后整块2的幂增益”。后者在一个820复数窗口内用同一移位，让最大I/Q分量不超过16383，移位范围-2..12；比较作用是防止第二次有缩放的IFFT把小数值压成少量整数码。增益不改变理论峰位置，其量化影响需要实测。

该增益需要T09局部820复数缓存和最大值归约，属于模块职责；缓存开销留后续RTL周期/资源测量，不引入T10跨阶段存储bank。幅度对照不授权修改T06/T08输入合同。

## 冻结运算
主FFT：2048正，pipelined，I16/Q16，twiddle16，convergent，fixed scaled，无BFP，stage0到5的右移[3,2,2,2,2,1]，总12位。
辅助FFT：最大16384、runtime N/direction，同样格式；研究使用2048逆和相同总12位右移。官方overflow必须记录并使最终valid=false。
A128补偿乘生产QPSK共轭只做一次，合并为八相旋转；系数S18/F16，乘加S35，RNE后S18。单位增益分支要求落入S16；幂增益分支整块移位后S16。
IFFT输出I16/Q16→精确U32功率→峰搜索±24采样→三点抛物线，delta用F16，延迟S24/F16。平峰、非负曲率、超半栅格拒绝插值。功率门3dB用ceil(10^(3/10)*2^24)比较，向严格方向量化，记录阈值；原first≤4、邻跳≤1、全74有效和fit RMSE≤0.25门不变。
LS用权重[-73,-71,...,73]。观察时刻等差17920，因此b=2*sum(w*dQ)/(17920*sum(w²)*2^16)。累加器检查S40；ppm numerator检查S80，denominator U49；输出S32/F18，所有除法符号对称ties-to-even。这次用大整数除法建立参考，RTL除法架构、延迟和资源待设计，不能据此声称面积合格。
拟合SSE采用整数有理式精确比较，无sqrt参与门判定。ppm→step沿既定Q18到Q28映射，不把浮点ppm直接送给补偿器。所有I/Q中间节点、峰三点、质量、位宽界、LS和step均保存。

## 结果解释与门槛
模型ABI/已有RTL逐整数控制、舍入小向量和零输入无效控制须先通过。研究矩阵即使目标失败也完整记录，不能选成功分支隐藏失败；普通范围/算法断言失败保留现场回交。
逐例报告浮点与整数ppm/延迟差、输入量化削顶、两FFT溢出、增益、有效率、理想步长残余。单例abs理想残余<0.1ppm只作为研究目标，不替代10种子分组MAE或实际第二遍波形。C11无效/上游削顶和C10补偿缺样继续分列，本包不修补这些既存限制。
完成后Astra选择必要修订或冻结候选，再安排量化统计及2–4个生产窗口的官方XSim对照；不直接启动大规模RTL。

## 执行冻结
唯一T09 Luna执行。1个受Windows Job监督的Python/C模型进程，0 MATLAB，0 Vivado；计划峰值内存2GiB，输出0.5GiB。预计3–10分钟，原生硬超时1200秒，取消60秒，根退出5秒清理。Python采用已安装私有运行时及reports/t09/design/review_python_deps的scipy；不改全局配置，DLL均包内私有加载。源码语法和包装器先静态检查，首次DLL加载及数值调用只能由Luna执行。
每次新attempt；包装/路径/依赖执行故障Luna在新修复版本自修并保存差异，不能改运算/输入/门槛。已完成案例不因交接重跑。运行清单记录实际命令/哈希、工具队列、监督器进程树及结果manifest，数学完成不等于PASS。
"""
planPath=R/"docs/t09/T09_FIXED007_PLAN_ZH.md";write(planPath,plan)
# Adapt proven job wrapper: same isolated Job ownership/cancellation, different native workload.
runner=(OLD/"run_t09_stats006.ps1").read_text(encoding="utf-8-sig")
runner=runner.replace("T09_STATS006","T09_FIXED007").replace("T09-STATS006","T09-FIXED007")
runner=rep(runner,"@('work','prefs','temp','results')","@('work','prefs','temp')")
start=runner.index("$matlab='");end=runner.index("$supervisor=",start)
runner=runner[:start]+"""$modelPython='C:\\Users\\lunan\\.cache\\codex-runtimes\\codex-primary-runtime\\dependencies\\python\\python.exe'
if(-not(Test-Path -LiteralPath $modelPython)){throw 'Frozen model Python missing'}
"""+runner[end:]
runner=runner.replace("'--stage','matlab'","'--stage','official_cmodel'").replace("matlab.stdout.log","model.stdout.log").replace("matlab.stderr.log","model.stderr.log")
runner=rep(runner,"$matlab,'-singleCompThread','-batch',$expr)","$modelPython,(Join-Path $package 't09_fixed007.py'),'--package',$package,'--output',(Join-Path $attempt 'results'))")
runner=rep(runner,"matlab_file_version=(Get-Item -LiteralPath $matlab).VersionInfo.FileVersion;","model_python=$modelPython;model_python_sha256=(Get-FileHash -LiteralPath $modelPython).Hash;")
runner=runner.replace("expected_minutes=@(3,8)","expected_minutes=@(3,10)").replace("matlab=1;vivado=0;planned_peak_memory_gib=8;output_budget_gib=2","python_cmodel=1;matlab=0;vivado=0;planned_peak_memory_gib=2;output_budget_gib=0.5")
runner=rep(runner,"$summary.case_count -ne 300 -or $summary.estimate_count -ne 600","$summary.case_count -ne 9 -or $summary.branch_count -ne 2")
runner=runner.replace("$caseFiles.Count -ne 300","$caseFiles.Count -ne 9").replace("@('nodes.mat','result.json')","@('integer_nodes.npz','result.json')")
runnerPath=R/"scripts/t09/run_t09_fixed007.ps1";write(runnerPath,runner)
for src,name in [(R/"scripts/t09/t09_fixed007.py","t09_fixed007.py"),(R/"scripts/t09/t09_xfft_cmodel007.py","t09_xfft_cmodel007.py"),
 (runnerPath,"run_t09_fixed007.ps1"),(OLD/"private_job_supervisor_t09_v3.py","private_job_supervisor_t09_v3.py"),
 (OLD/"evidence/accepted_wrapper_probe_exit.json","evidence/accepted_wrapper_probe_exit.json"),(planPath,"PLAN_ZH.md"),
 (reviewPath,"evidence/STATS006_REVIEW_ZH.md"),(R/"reports/t09/design/T09_STATS006/INDEPENDENT_REVIEW.json","evidence/STATS006_INDEPENDENT_REVIEW.json"),
 (R/"scripts/t09/review_t09_stats006.py","evidence/review_t09_stats006.py"),(STATS/"results/pilot_contract.mat","inputs/pilot_contract.mat")]:add(src,name)
# Vendor archive private copy; keep all supplied notices untouched.
vendor=Path(r"C:\NIFPGA\programs\Vivado2021_1\data\ip\xilinx\xfft_v9_1\cmodel\xfft_v9_1_bitacc_cmodel_nt64.zip")
add(vendor,"vendor_archive.zip")
with zipfile.ZipFile(vendor) as z:
    for n in z.namelist():
        assert Path(n).name==n
        p=PKG/"vendor"/n;p.parent.mkdir(exist_ok=True);p.write_bytes(z.read(n));generated("vendor/"+n)
# Parent result manifests bind the reused MAT/result files.
def checked_result(attempt,relative):
    rows=read(attempt/"result_manifest.json")
    row=next(r for r in rows if r["path"].replace("\\","/")==relative)
    p=attempt/relative;assert sha(p)==row["sha256"].upper();return p
cases=[]
for number,scale in [(41,32768),(91,32768),(271,32768),(291,32768),(41,263403)]:
    name=f"inputs/stats_{number:03d}_nodes.mat"
    if not (PKG/name).exists():
        add(checked_result(STATS,f"results/case_{number:03d}/nodes.mat"),name)
        add(checked_result(STATS,f"results/case_{number:03d}/result.json"),name.replace("_nodes.mat","_result.json"))
    d=read(STATS/f"results/case_{number:03d}/result.json")
    cases.append(dict(domain="conditional",id=f"stats_{number:03d}_scale_{scale}",nodes=name,
        input_code_scale=scale,input_residual_ppm=d["definition"]["residual_ppm"],source_definition=d["definition"],
        upstream_supported_accuracy_not_claimed=True))
for base,number in [("T09_CLOSED002_rev02/attempt_20260908T211456489Z_luna",1),("T09_CLOSED003_rev02/attempt_20260908T214146142Z_luna",1),
 ("T09_CLOSED005/attempt_20260908T221857075Z_luna",2),("T09_CLOSED005/attempt_20260908T221857075Z_luna",3)]:
    attempt=R/"reports/t09/execution"/base;d=read(attempt/f"results/case_{number:03d}/result.json");fid=d["frame_id"]
    name=f"inputs/frame_{fid}_nodes.mat"
    add(checked_result(attempt,f"results/case_{number:03d}/first_nodes.mat"),name)
    add(checked_result(attempt,f"results/case_{number:03d}/result.json"),f"inputs/frame_{fid}_result.json")
    cases.append(dict(domain="actual_first_integer_output",id=f"frame_{fid}",nodes=name,input_code_scale=32768,
        input_residual_ppm=d["initial_residual_rate_truth_ppm"],upstream_limitations_retained=fid in (6010,6011),
        source_attempt=str(attempt),window_unit="Existing signed16 integer code divided by 32768; multiplication restores exact saved code"))
jsonfile(PKG/"study.json",dict(cases=cases,backend_padding=2,mode_count=2,T09_PASS=False));generated("study.json")
# Extract controls only; no FFT/model execution in this builder.
controlDir=PKG/"controls";controlDir.mkdir()
controls=[];provenance=[]
t06=R/"reports/T06_initial_sfo/v2_official_xfft_trace/attempt_20260902T142609651Z_12196_721808b0"
rows=list(csv.DictReader((t06/"artifact_manifest.csv").open(encoding="utf-8-sig",newline="")))
selected=[0,7,355,711];ins={x:[] for x in selected};outs={x:[] for x in selected}
def parent(p,role):
    h=sha(p);provenance.append(dict(path=str(p),role=role,sha256=h,bytes=p.stat().st_size));return h
def decode(line):
    v=int(line.strip(),16);i=v&65535;q=(v>>16)&65535
    return [i-65536 if i>=32768 else i,q-65536 if q>=32768 else q]
for role in ("input_mem","full_output_trace"):
    row=next(r for r in rows if r["role"]==role);p=Path(row["path"]);assert parent(p,role)==row["sha256"].upper()
with (t06/"fixture/t06_v2_official_xfft_input.mem").open() as f:
    for i,line in enumerate(f):
        if i//2048 in ins:ins[i//2048].append(decode(line))
with (t06/"official_xfft_simulation/t06_v2_official_xfft_output.csv").open(newline="") as f:
    for row in csv.DictReader(f):
        j=int(row["JobIndex"])
        if j in outs:
            assert int(row["BinIndex"])==len(outs[j]) and int(row["Overflow"])==0
            outs[j].append([int(row["I"]),int(row["Q"])])
for j in selected:
    assert len(ins[j])==len(outs[j])==2048
    name=f"controls/main_job_{j}.npz";np.savez(PKG/name,input=np.array(ins[j],np.int16),expected=np.array(outs[j],np.int16));generated(name)
    controls.append(dict(id=f"main_job_{j}",engine="main",path=name,forward=True,schedule=[3,2,2,2,2,1]))
for src,name in [(t06/"completion.json","evidence/T06_OFFICIAL_FFT_COMPLETION.json"),(t06/"artifact_manifest.csv","evidence/T06_ARTIFACT_MANIFEST.csv"),
 (t06/"official_xfft_xci/t03_xfft_2048_main.xci","evidence/main_fft.xci")]:add(src,name)
aux=R/"reports/T03_realtime_memory_fft/auxiliary_fft_runtime"
mem=aux/"vec_r02/auxiliary_fft_input.mem";trace=aux/"vn02/auxiliary_fft_rtl_output.csv"
parent(mem,"auxiliary_input");parent(trace,"auxiliary_post_synthesis_output")
ai=np.array([decode(x) for x in mem.read_text().splitlines()],np.int16)
ar=list(csv.DictReader((aux/"vec_r02/auxiliary_fft_vector_manifest.csv").open(newline="")))
ao={int(r["Frame"]):[] for r in ar}
with trace.open(newline="") as f:
    for row in csv.DictReader(f):
        j=int(row["Frame"]);assert int(row["Bin"])==len(ao[j]);ao[j].append([int(row["I"]),int(row["Q"])])
offset=0
for c in ar:
    j=int(c["Frame"]);n=int(c["Length"]);assert len(ao[j])==n
    name=f"controls/aux_frame_{j}.npz";np.savez(PKG/name,input=ai[offset:offset+n],expected=np.array(ao[j],np.int16));generated(name)
    offset+=n;sch=int(c["ScaleSchedule"],16);stages=(n.bit_length()-1+1)//2
    controls.append(dict(id=f"aux_frame_{j}",engine="aux",path=name,forward=bool(int(c["Forward"])),schedule=[(sch>>(2*i))&3 for i in range(stages)]))
assert offset==61440
for suffix in ("vec_r02/auxiliary_fft_vector_manifest.csv","cmpn_r01/auxiliary_fft_matlab_rtl_metrics.csv","cmpn_r01/T03_AUX_XFFT_MATLAB_RTL_COMPARE_PASS.txt","automatic_final_gate.txt"):
    add(aux/suffix,"evidence/aux_"+Path(suffix).name)
jsonfile(PKG/"controls/controls.json",dict(controls=controls,parents=provenance,selected_main_jobs=selected));generated("controls/controls.json")
add(Path(__file__),"evidence/build_t09_fixed007_package.py")
for name in ("t09_fixed007.py","t09_xfft_cmodel007.py","private_job_supervisor_t09_v3.py"):ast.parse((PKG/name).read_text(encoding="utf-8-sig"))
jsonfile(PKG/"manifest.json",dict(schema="T09_FIXED007_PACKAGE_v1",job_id="T09-FIXED007",files=records,created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat()))
mh=sha(PKG/"manifest.json");jsonfile(PKG/"COMPLETE.json",dict(complete=True,frozen_file_count=len(records),manifest_sha256=mh))
dispatch=dict(job_id="T09-FIXED007",status="READY_FOR_DISPATCH",astra_thread_id="01a08299-4a14-7ef0-9000-50ec54cfdce2",
 luna_thread_id="01a08298-b5b6-79b3-b5b4-18b8ac68993a",package_root=str(PKG),manifest_sha256=mh,frozen_file_count=len(records),
 command_argv=[r"C:\Users\lunan\.cache\codex-runtimes\codex-primary-runtime\dependencies\native\powershell\pwsh.exe","-NoProfile","-File",str(PKG/"run_t09_fixed007.ps1"),"-PackageRoot",str(PKG),"-ExpectedManifestSha256",mh],
 resources=dict(python_cmodel=1,matlab=0,vivado=0,planned_peak_memory_gib=2,planned_output_gib=.5),
 expected_minutes=[3,10],native_hard_timeout_seconds=1200,cancel_cleanup_seconds=60,case_count=9,branch_count=2,bridge_control_count=12,T09_PASS=False)
jsonfile(BASE/"DISPATCH.json",dispatch)
for f in records:assert sha(PKG/f["path"])==f["sha256"]
print(json.dumps(dict(files=len(records),manifest_sha256=mh,dispatch=str(BASE/"DISPATCH.json")),indent=2))