"""Generate/check the direct VHDL wrapper against the selected SV header.
This is text-level interface inspection, not VHDL compilation or simulation.
"""
from pathlib import Path
import argparse,json,re
ROOT=Path(__file__).resolve().parents[2]
def ports():
    header=(ROOT/'rtl/control/sync_ota_top_v51.sv').read_text().split('module sync_ota_top(',1)[1].split(');',1)[0]
    result=[];direction=None;width=None
    for field in header.split(','):
        field=field.strip()
        m=re.fullmatch(r'(input|output)\s+(?:wire|logic)\s*(\[\d+:\d+\])?\s*(\w+)',field)
        if m:direction,width,name=m.groups()
        else:
            if not re.fullmatch(r'\w+',field) or direction is None:raise ValueError(field)
            name=field
        result.append({'name':name,'direction':direction,'width':int(width[1:-1].split(':')[0])+1 if width else 1})
    return result
def generate(ps):
    def decl(x):
        typ='std_logic' if x['width']==1 else f"std_logic_vector({x['width']-1} downto 0)"
        return f"    {x['name']} : {'in' if x['direction']=='input' else 'out'} {typ}"
    declarations=';\n'.join(decl(x) for x in ps)
    mapping=',\n'.join(f"      {x['name']} => {x['name']}" for x in ps)
    return f"""-- V5.1 Sync_OTA: every output_valid beat transfers at clk150.
-- No output ready or intermediate DDR interface. All clocks run during reset.
-- stream_first/last mark independent input segments, not algorithm frames.
-- See docs/v51/INTERFACE_CONTRACT_ZH.md. Generated by tools/v51/wrapper_interface.py.
library ieee;
use ieee.std_logic_1164.all;
entity sync_ota_wrapper is
  port(
{declarations}
  );
end entity;
architecture rtl of sync_ota_wrapper is
  component sync_ota_top is
    port(
{declarations}
    );
  end component;
begin
  core : sync_ota_top
    port map(
{mapping}
    );
end architecture;
"""
def main():
    p=argparse.ArgumentParser();p.add_argument('--write',action='store_true');p.add_argument('--output',type=Path,required=True);a=p.parse_args()
    ps=ports();expected=generate(ps);target=ROOT/'wrapper/sync_ota_wrapper.vhd'
    if a.write:target.write_text(expected,encoding='utf-8',newline='\n')
    match=target.read_text()==expected
    report={'evidence':'STATIC_PORT_AND_DIRECT_MAPPING_INSPECTION','top':'sync_ota_top','port_count':len(ps),'wrapper_matches':match,'ports':ps,'vhdl_compile':'NOT_RUN'}
    a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8',newline='\n')
    print(json.dumps({'port_count':len(ps),'wrapper_matches':match}));return int(not match)
if __name__=='__main__':raise SystemExit(main())
